---
- name: Install and configure WordPress on Rocky Linux 8
  hosts: all
  become: true

  tasks:
    - name:
      include_vars: wp_vars.yml

    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - httpd
        - mariadb
        - mariadb-server
        - php
        - php-mysqli
        - php-gd
        - php-xml
        - php-mbstring
        - php-json
        - php-curl
        - php-dom
        - php-exif
        - php-fileinfo
        - php-imagick
        - php-openssl
        - python3-PyMySQL
        - ssh2
        - ftp
        - sockets
        - ImageMagick

    - name: Start and enable services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items:
        - httpd
        - mariadb

    - name: Set up MariaDB root password
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: ""
        host_all: true
        check_implicit_admin: true

    - name: Create WordPress database and user
      mysql_db:
        name: "{{ wordpress_database_name }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create a new MariaDB user for WordPress
      mysql_user:
        name: "{{ wordpress_database_user }}"
        password: "{{ wordpress_database_password }}"
        priv: "{{ wordpress_database_name }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Download and extract WordPress
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: /tmp/wordpress.tar.gz
      become: true
    - name: Extract WordPress archive
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: true
      become: true
    - name: Set appropriate file permissions
      file:
        path: /var/www/html/wordpress
        state: directory
        mode: "0755"
        recurse: yes
      become: true

    - name: Copy WordPress configuration file
      template:
        src: wp-config.php.j2
        dest: /var/www/html/wordpress/wp-config.php
        mode: 0644
      become: true

    - name: Update Apache virtual host file
      template:
        src: wordpress.conf.j2
        dest: /etc/httpd/conf.d/wordpress.conf
        mode: 0644

    - name: Restart Apache
      systemd:
        name: httpd
        state: restarted
