
---

- hosts: localhost 

  name: suspend_vms
  connection: local
  gather_facts: false
  collections:
    - community.vmware

  pre_tasks:
    - include_vars: vm_moid_testing.yml

  tasks:

  - name: Restore power to suspended VMs
    vmware_guest_powerstate:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vcenter_datacenter }}"
      moid: "{{ item }}"
      state: powered-on
      force: true
      validate_certs: no
    with_items: "{{ vm_moid }}"
    delegate_to: localhost

     
