---

- name: check and install updates - CentOS
  yum: 
    update_cache: true
    name: '*' 
    state: latest
  when: ansible_distribution == "CentOS"

- name: check and install updates - Rocky
  dnf:
    update_cache: true
    name: '*'
    state: latest
  when: ansible_distribution == "Rocky"
