
---

- hosts: localhost 

  name: snapshot
  connection: local
  gather_facts: false
  collections:
    - community.vmware

  pre_tasks:
    - include_vars: prod_vars.yml

  tasks:

  - name: Remove a snapshot
    vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vcenter_datacenter }}"
      moid: "{{ item }}"
      state: remove_all
      validate_certs: no
    with_items: "{{ vm_moid }}"
    delegate_to: localhost

  - name: Create a snapshot
    community.vmware.vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vcenter_datacenter }}"
      moid: "{{ item }}"
      quiesce: true
      state: present
      snapshot_name: Pre-Patch 
      description: "CYA - Recover point before patching"
      validate_certs: no
    with_items: "{{ vm_moid }}"
    delegate_to: localhost

     
